variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - dmenv install
  - export PATH=$(dmenv show:venv_path)/bin:$PATH
  - dmenv run -- python run-ci.py --isolate-conan-user-home update-conan-config

stages:
  - check
  - deploy

.testreports:
  artifacts:
    paths:
      - tests_report
    expire_in: 1 month

check/deployed-native:
  extends: .testreports
  when: manual
  stage: check
  except:
    - tags
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed
  tags:
    - linux

check/native-from-sources:
  extends: .testreports
  when: manual
  stage: check
  except:
    - tags
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch
  tags:
    - linux

nightly:
  stage: check
  only:
    - schedules
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch
  tags:
    - linux

deploy:
  extends: .testreports
  stage: deploy
  only:
    - tags
  when: manual
  script:
    - dmenv run -- python run-ci.py  --isolate-conan-user-home deploy --git-tag ${CI_COMMIT_TAG}
  tags:
    - linux

mirror:
  tags:
    - linux
  stage: deploy
  only:
    # mirror public tags, releases branches
    # feature branches, and master
    - /\Av[0-9.]+\z/
    - master
    - /\Arelease/.*\z/
    - /\Afeat\/.+\z/   # feat/ branches
  except:
    - schedules
  script:
    - dmenv run python run-ci.py mirror
