include:
  - project: TankerHQ/gitlab-ci-files
    ref: 21ee71ff504eb0d9171f06bae9d77e106dfac35f
    file: /android.yml

###############
# check stage #
###############

check/deployed-native:
  extends:
    - .check
    - .testreports
    - .rules/deployed-native
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed

check/native-from-sources:
  extends:
    - .check
    - .testreports
    - .rules/native-from-sources
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch

check/downstream:
  extends:
    - .check
    - .before-script/download-artifacts
    - .rules/check/downstream
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=upstream

################
# deploy stage #
################

deploy:
  extends:
    - .deploy
    - .rules/deploy/android
  script:
    - poetry run python run-ci.py --isolate-conan-user-home deploy --version $SDK_ANDROID_RELEASE_VERSION
  release:
    description: sdk-android v$SDK_ANDROID_RELEASE_VERSION
    tag_name: v$SDK_ANDROID_RELEASE_VERSION

mirror:
  extends:
    - .deploy
    - .rules/mirror
  script:
    - poetry run python run-ci.py mirror
