include:
  - project: TankerHQ/gitlab-ci-files
    ref: 37bb68d38359db981eaec61aa6918075ff29d4e0
    file: /android.yml

###############
# check stage #
###############

.dump-test-results:
  artifacts:
    when: always
    paths:
      - tanker-bindings/build/reports
    expire_in: 30 days

check/deployed-native:
  extends:
    - .check
    - .testreports
    - .rules/deployed-native
    - .dump-test-results
  script:
    - sudo chgrp 1000 -f /dev/kvm
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed --tanker-ref=$SDK_NATIVE_LATEST_CONAN_REFERENCE

check/native-from-sources:
  extends:
    - .check
    - .testreports
    - .rules/native-from-sources
    - .dump-test-results
  script:
    - sudo chgrp 1000 -f /dev/kvm
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch

check/downstream:
  extends:
    - .check
    - .before-script/download-artifacts
    - .rules/check/downstream
    - .dump-test-results
  script:
    - sudo chgrp 1000 -f /dev/kvm
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=upstream

################
# deploy stage #
################

deploy:
  extends:
    - .deploy
    - .rules/deploy/android
  script:
    - sudo chgrp 1000 -f /dev/kvm
    - poetry run python run-ci.py --isolate-conan-user-home deploy --version $SDK_ANDROID_RELEASE_VERSION --tanker-ref $SDK_NATIVE_LATEST_CONAN_REFERENCE
  release:
    description: sdk-android v$SDK_ANDROID_RELEASE_VERSION
    tag_name: v$SDK_ANDROID_RELEASE_VERSION

mirror:
  extends:
    - .deploy
    - .rules/mirror
  script:
    - poetry run python run-ci.py mirror
