include:
  - project: TankerHQ/gitlab-ci-files
    ref: 2023-05-25-262
    file: /common.yml

variables:
  SDK_NATIVE_CONAN_REFERENCE: tanker/latest-stable@
  GIT_DEPTH: 1

############
# Workflow #
############

workflow:
  rules:
    # web pipelines for releases only
    - if: $CI_PIPELINE_SOURCE == "web" && $SDK_ANDROID_RELEASE_VERSION !~ /\A\d+\.\d+\.\d+(-(alpha|beta)-\d+)?\z/
      when: never
    - if: !reference [.if-invalid-native-conan-reference, if]
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        CONAN_REMOTE: "artifactory"
    - if: '$CI_MERGE_REQUEST_TITLE =~ /.*\[preview].*/'
      variables:
        CONAN_REMOTE: "artifactory-preview"
    - when: always
      variables:
        CONAN_REMOTE: "artifactory-staging"

###########
# Default #
###########

default:
  before_script: &global_before_script
    - poetry run python -m pip install --upgrade pip
    - poetry install
  image: registry.gitlab.com/tankerhq/docker/sdk-android:latest

##########
# Stages #
##########

stages:
  - check
  - bridge-check
  - deploy

#############################
# Default settings override #
#############################

.before-script/download-artifacts:
  before_script:
    - *global_before_script
    - poetry run python run-ci.py download-artifacts --project-id=$UPSTREAM_PROJECT_ID --pipeline-id=$UPSTREAM_PIPELINE_ID --job-name=$UPSTREAM_JOB_NAME
    - poetry run python run-ci.py reset-branch $(cat branch_name.txt)
    - poetry run python -m pip install --upgrade pip
    - poetry install

###############
# check stage #
###############

.artifacts:
  artifacts:
    when: always
    paths:
      - artifacts
      - branch_name.txt
      - screenshot.png

.rules/check/deployed-native:
  rules:
    - !reference [.rules/web/auto, rules]
    - !reference [.rules/mr/manual, rules]

check/deployed-native:
  extends:
    - .rules/check/deployed-native
    - .artifacts
  stage: check
  script:
    - sudo chgrp 1000 -f /dev/kvm
    - poetry run python run-ci.py --remote $CONAN_REMOTE --isolate-conan-user-home build-and-test --use-tanker=deployed --tanker-ref=$SDK_NATIVE_LATEST_CONAN_REFERENCE
    - echo $CI_COMMIT_REF_NAME > branch_name.txt
  tags: !reference [.tags/compilation-linux, tags]

check/native-from-sources:
  extends:
    - .rules/native-from-sources
    - .artifacts
  stage: check
  script:
    - sudo chgrp 1000 -f /dev/kvm
    - poetry run python run-ci.py --remote $CONAN_REMOTE --isolate-conan-user-home build-and-test --use-tanker=same-as-branch
    - echo $CI_COMMIT_REF_NAME > branch_name.txt
  tags: !reference [.tags/compilation-linux, tags]

check/downstream:
  extends:
    - .before-script/download-artifacts
    - .rules/check/downstream
    - .artifacts
  stage: check
  script:
    - sudo chgrp 1000 -f /dev/kvm
    - poetry run python run-ci.py --remote $CONAN_REMOTE --isolate-conan-user-home build-and-test --use-tanker=upstream
  tags: !reference [.tags/compilation-linux, tags]

######################
# bridge-check stage #
######################

bridge-dotenv:
  stage: bridge-check
  inherit:
    default: [] # Skip docker image
  rules:
    - !reference [ .rules/push-master-or-feat, rules ]
    - !reference [ .rules/check/downstream/android, rules ]
    - !reference [ .rules/mr/manual, rules ]
    - !reference [ .rules/nightly, rules ]
  before_script:
    - *global_before_script
  script:
    - poetry run python run-ci.py write-bridge-dotenv --downstream compatibility-tests
  artifacts:
    expire_in: 7 days
    reports:
      dotenv: bridge.env
  tags: !reference [.tags/linux, tags]

bridge/compat-from-sources:
  stage: bridge-check
  extends:
    - .variables/bridge-common
    - .rules/native-from-sources
  needs:
    - check/native-from-sources
    - bridge-dotenv
  variables:
    UPSTREAM_JOB_NAME: check/native-from-sources
    UPSTREAM_JOB_TARGET: android
    UPSTREAM_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME
  trigger:
    project: TankerHQ/compatibility-tests
    branch: $COMPATIBILITY_TESTS_BRIDGE_BRANCH
    strategy: depend

bridge/compat-downstream:
  stage: bridge-check
  extends:
    - .variables/bridge-common
  rules:
    - if: !reference [.if-upstream-ci-pipeline, if]
  needs:
    - check/downstream
    - bridge-dotenv
  variables:
    UPSTREAM_JOB_NAME: check/downstream
    UPSTREAM_JOB_TARGET: android
    UPSTREAM_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME
  trigger:
    project: TankerHQ/compatibility-tests
    branch: $COMPATIBILITY_TESTS_BRIDGE_BRANCH
    strategy: depend

bridge/compat-deployed:
  stage: bridge-check
  extends:
    - .variables/bridge-common
  rules:
    # only run during standalone SDK releases
    - if: !reference [.if-invalid-android-release-version, if]
      when: never
    - !reference [.rules/web/auto, rules]
  needs:
    - check/deployed-native
    - bridge-dotenv
  variables:
    SDK_NATIVE_LATEST_CONAN_REFERENCE: $SDK_NATIVE_LATEST_CONAN_REFERENCE
    UPSTREAM_JOB_NAME: check/deployed-native
    UPSTREAM_JOB_TARGET: android
    UPSTREAM_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME
  trigger:
    project: TankerHQ/compatibility-tests
    branch: $COMPATIBILITY_TESTS_BRIDGE_BRANCH
    strategy: depend

################
# deploy stage #
################

deploy:
  extends:
    - .rules/deploy/android
  stage: deploy
  script:
    - sudo chgrp 1000 -f /dev/kvm
    - poetry run python run-ci.py reset-branch $UPSTREAM_BRANCH_NAME
    - poetry run python run-ci.py --remote $CONAN_REMOTE --isolate-conan-user-home deploy --version $SDK_ANDROID_RELEASE_VERSION --tanker-ref $SDK_NATIVE_LATEST_CONAN_REFERENCE
  release:
    description: sdk-android v$SDK_ANDROID_RELEASE_VERSION
    tag_name: v$SDK_ANDROID_RELEASE_VERSION
  tags: !reference [.tags/compilation-linux, tags]

brige/bump-android-compat-tests:
  stage: deploy
  extends:
    - .variables/bridge-common
  rules:
    - if: !reference [.if-invalid-android-release-version, if]
      when: never
    - if: !reference [.if-web-pipeline, if]
      when: manual
    - if: !reference [.if-upstream-release-deploy-stage, if]
      when: manual
  needs:
    - deploy
    - bridge-dotenv
  variables:
    SDK_ANDROID_RELEASE_VERSION: $SDK_ANDROID_RELEASE_VERSION
    SDK_NATIVE_LATEST_CONAN_REFERENCE: $SDK_NATIVE_LATEST_CONAN_REFERENCE
    UPSTREAM_JOB_NAME: deploy
    UPSTREAM_JOB_TARGET: android
    UPSTREAM_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME
  trigger:
    project: TankerHQ/compatibility-tests
    branch: $COMPATIBILITY_TESTS_BRIDGE_BRANCH
    strategy: depend
  allow_failure: true
