image: tanker.local:5000/ci-android:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - dmenv install
  - export PATH=$(dmenv show:venv_path)/bin:$PATH
  - dmenv run -- python run-ci.py update-conan-config --platform linux

stages:
  - check
  - deploy

check/deployed-native:
  when: manual
  stage: check
  except:
    - tags
  script:
    - dmenv run -- python run-ci.py check
  tags:
    - linux

check/native-from-sources:
  when: manual
  stage: check
  except:
    - tags
  script:
    - dmenv run -- python run-ci.py check --native-from-sources
  tags:
    - linux


deploy:
  stage: deploy
  only:
    - tags
  when: manual
  script:
    - dmenv run -- python run-ci.py deploy --git-tag ${CI_COMMIT_TAG}
  tags:
    - linux

mirror:
  tags:
    - linux
  stage: deploy
  only:
    - /\Av[0-9.]+\z/   # public release tags only
    - master
  except:
    - schedules
  script:
    - dmenv run python run-ci.py mirror
