include:
  - project: TankerHQ/gitlab-ci-files
    ref: a86a57362301a6e734240a0f056f83285924ba0b
    file: /android.yml

###############
# check stage #
###############

.dump-test-results:
  artifacts:
    when: always
    paths:
      - tanker-bindings/build/reports
    expire_in: 30 days

check/deployed-native:
  extends:
    - .check
    - .tags/linux
    - .rules/deployed-native
    - .dump-test-results
  script:
    - sudo chgrp 1000 -f /dev/kvm
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed --tanker-ref=$SDK_NATIVE_LATEST_CONAN_REFERENCE
  artifacts:
    paths:
      - artifacts

check/native-from-sources:
  extends:
    - .check
    - .tags/linux
    - .rules/native-from-sources
    - .dump-test-results
  script:
    - sudo chgrp 1000 -f /dev/kvm
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch
  artifacts:
    paths:
      - artifacts

check/downstream:
  extends:
    - .check
    - .tags/linux
    - .before-script/download-artifacts
    - .rules/check/downstream
    - .dump-test-results
  script:
    - sudo chgrp 1000 -f /dev/kvm
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=upstream
  artifacts:
    paths:
      - artifacts

######################
# bridge-check stage #
######################

bridge/native-from-sources:
  extends:
    - .bridge-check
    - .rules/native-from-sources
    - .variables/bridge-common
  needs:
    - check/native-from-sources
  variables:
    UPSTREAM_JOB_NAME: check/native-from-sources
    UPSTREAM_JOB_TARGET: android
  trigger:
    project: TankerHQ/sdk-react-native
    strategy: depend

bridge/downstream:
  extends:
    - .bridge-check
    - .rules/check/downstream
    - .variables/bridge-common
  needs:
    - check/downstream
  variables:
    UPSTREAM_JOB_NAME: check/downstream
    UPSTREAM_JOB_TARGET: android
  trigger:
    project: TankerHQ/sdk-react-native
    strategy: depend

bridge/deployed-native:
  extends:
    - .bridge-check
    - .rules/deployed-native
    - .variables/bridge-common
  needs:
    - check/deployed-native
  variables:
    UPSTREAM_JOB_NAME: check/deployed-native
    UPSTREAM_JOB_TARGET: android
  trigger:
    project: TankerHQ/sdk-react-native
    strategy: depend

################
# deploy stage #
################

deploy:
  extends:
    - .deploy
    - .tags/linux
    - .rules/deploy/android
  script:
    - sudo chgrp 1000 -f /dev/kvm
    - poetry run python run-ci.py --isolate-conan-user-home deploy --version $SDK_ANDROID_RELEASE_VERSION --tanker-ref $SDK_NATIVE_LATEST_CONAN_REFERENCE
  release:
    description: sdk-android v$SDK_ANDROID_RELEASE_VERSION
    tag_name: v$SDK_ANDROID_RELEASE_VERSION

mirror:
  extends:
    - .deploy
    - .rules/mirror
  script:
    - poetry run python run-ci.py mirror
