[tool.poetry]
name = "sdk-android"
version = "0.1.0"
description = "Android bindings for the Tanker SDK"
authors = ["Tanker team <tech@tanker.io>"]

[tool.poetry.dependencies]
python = "^3.7"
ci = "2020.2.2093"


[tool.poetry.dev-dependencies]


[[tool.poetry.source]]
name = "tanker.local"
url = "http://tanker.local:8181"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
