[tool.poetry]
name = "sdk-android"
version = "0.1.0"
description = "Android bindings for the Tanker SDK"
authors = ["Tanker team <tech@tanker.io>"]

[tool.poetry.dependencies]
python = "^3.7"
ci = { git = "git+ssh://git@tanker.local/Tanker/ci", branch = "master" }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
