[version]
current = "dev"

regex = '''
  (dev)
  |
    (
    (?P<major>\d+)
    \.
    (?P<minor>\d+)
    \.
    (?P<patch>\d+)
    (
      -
      (?P<channel>alpha|beta|r)
      -
      (?P<release>\d+)
    )?
  )
'''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "tanker-bindings/build.gradle"
search = "version '{current_version}'"


[[file]]
src = "tanker-bindings/src/main/kotlin/io/tanker/api/Tanker.kt"
search = 'TANKER_ANDROID_VERSION = "{current_version}"'

[[file]]
src = "tanker-bindings/src/main/kotlin/io/tanker/api/TankerOptions.kt"
search = 'sdkVersion: String = "{current_version}"'
