package io.tanker.bindings

/**
 * Error codes in a TankerError
 * @see TankerError
 */
enum class TankerErrorCode(val value: Int) {
    NO_ERROR(0),
    OTHER(1),
    INVALID_TANKER_STATUS(2),
    SERVER_ERROR(3),
    INVALID_VALIDATION_CODE(4),
    INVALID_ARGUMENT(5),
    RESOURCE_KEY_NOT_FOUND(6),
    USER_NOT_FOUND(7),
    DECRYPT_FAILED(8),
    INVALID_DEVICE_VALIDATION_EVENT_HANDLER(9),
    CHUNK_INDEX_OUT_OF_RANGE(10),
    VERSION_NOT_SUPPORTED(11),
    INVALID_UNLOCK_KEY(12),
    INTERNAL_ERROR(13),
    CHUNK_NOT_FOUND(14),
    INVALID_UNLOCK_PASSWORD(15),
    INVALID_VERIFICATION_CODE(16),
    UNLOCK_KEY_ALREADY_EXISTS(17),
    MAX_VERIFICATION_ATTEMPTS_REACHED(18),
    INVALID_GROUP_SIZE(19),
    RECIPIENT_NOT_FOUND(20),
    GROUP_NOT_FOUND(21),
    DEVICE_NOT_FOUND(22),
}
